from crewai import Agent, Task, Crew
from crewai_tools import MCPServerAdapter
from config.config import server_params
from src.utils import get_llm_model
from src.tools.Retriever_Tool import GetRelevantDocumentsTool
from src.tools.Diagram_Tool import GenerateDiagramTool


class FeedbackAgent:
    def __init__(self):
        self.llm = get_llm_model()
        self.mcp_adapter = MCPServerAdapter(server_params, connect_timeout=120)
        self.agent = self._initialize_agent()
    
    def _initialize_agent(self):

        mcp_tools = self.mcp_adapter.__enter__()  # explicitly open the adapter

        kb_tool = GetRelevantDocumentsTool()
        diagram_tool = GenerateDiagramTool()

        tools = [kb_tool, diagram_tool] + list(mcp_tools)

        self.agent = Agent(
            llm = self.llm,
            tools = tools,
            role = "Feedback Agent - Evaluate Math Solutions",
            goal = (
                "Evaluate the correctness and clarity of mathematical solutions provided by MathGPT. "
                "user provides the feed back on the solutions procided by MathGPT. "
                "based on the user feedback,generate an improved solutions which addresses the user's concerns and make sure the solution is compatible for students."
            ),
            backstory = (
                "You are an expert mathematics tutor specializing in Resolving the issues raised by students regarding solutions provided by MathGPT. "
                "Your role is to assess the solutions generated by MathGPT, ensuring they are accurate, clear, and pedagogically sound. "
                "You will use internal knowledge and external web search tools to verify facts and enhance explanations as needed."
            ),

        )
        return self.agent
    def run_agent(self, original_query: str, mathgpt_solution: str, user_feedback: str):
        """
        Run the feedback agent to evaluate and improve MathGPT's solution.
        """

        task = Task(
            description=f"""
            You are provided with an original math query, the solution generated by MathGPT, and feedback from a user regarding that solution. 
            Your task is to evaluate the solution based on the user's feedback and generate an improved version of the solution that addresses the concerns raised.

            Original Query:
            {original_query}
            
            MathGPT's Solution:
            {mathgpt_solution}

            User Feedback:
            {user_feedback}
            """,
            agent=self.agent,
            expected_output="A clear, improved mathematical solution in Markdown format with LaTeX notation that addresses the user's feedback and provides better clarity, accuracy, or explanation as needed."
        )
        

        crew = Crew(
            agents=[self.agent],
            tasks=[task]
        )

        results = crew.kickoff({
            "original_query": original_query,
            "mathgpt_solution": mathgpt_solution,
            "user_feedback": user_feedback
        })

        # Extract string from CrewOutput object
        if hasattr(results, 'tasks_output') and results.tasks_output:
            return str(results.tasks_output[-1])
        elif hasattr(results, 'raw'):
            return str(results.raw)
        else:
            return str(results)
    
    def close(self):
        """Cleanly shut down the MCP adapter."""
        if self.mcp_adapter:
            self.mcp_adapter.__exit__(None, None, None)